/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sombrero_superficie_math.gltf
Author: rosaliarenda (https://sketchfab.com/rosaliarenda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sombrero-superficie-math-1260e7bebd0545e19c9578744c5b2b68
Title: Sombrero - Superficie Math
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sombrero_superficie_math.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Z_Function007_Material003_0.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Z_Function007_Material003_0_1.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/sombrero_superficie_math.gltf')
